version: '3'
services:
  front:
    build:
      context: './react-docker'
      dockerfile: Dockerfile
    ports:
      - 3000:3000
    container_name: react-container
    environment:
      - WATCHPACK_POLLING=true
    networks:
      - mern-profile-network
    volumes:
      - ./react-docker:/app
    depends_on:
      - backend
  backend:
    build:
      context: './server'
      dockerfile: Dockerfile
    ports:
      - 5000:5000
    container_name: server-container
    networks:
      - mern-profile-network
    volumes:
      - ./server:/app
    depends_on:
      - mongo
  mongo:
    image: mongo
    ports:
      - 27017:27017
    container_name: mongo-container
    networks:
      - mern-profile-network
    volumes:
      - mongoData:/data/db
    environment:
      - MONGO_INITDB_ROOT_USERNAME=<use .env file instead>
      - MONGO_INITDB_ROOT_PASSWORD=<use .env file instead>
      - MONGO_INITDB_DATABASE=profile
networks:
  mern-profile-network:
volumes:
  mongoData:
